"""user rating relationship added in book

Revision ID: 0c3ee3dd04a2
Revises: 50cf2718bcc3
Create Date: 2023-06-24 12:39:32.557375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3ee3dd04a2'
down_revision = '50cf2718bcc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
