"""user rating model modified

Revision ID: 50cf2718bcc3
Revises: b6297fbea00a
Create Date: 2023-06-24 12:36:33.748481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cf2718bcc3'
down_revision = 'b6297fbea00a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
