"""Initial migration

Revision ID: e2b4ec1f870f
Revises: 
Create Date: 2023-06-15 15:54:16.041428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b4ec1f870f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_book_history', sa.Column('action', sa.Enum('BORROW', 'RETURN', name='action_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_book_history', 'action')
    # ### end Alembic commands ###
