"""Description of changes

Revision ID: e937f788eb91
Revises: e2b4ec1f870f
Create Date: 2023-06-15 15:55:43.696544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e937f788eb91'
down_revision = 'e2b4ec1f870f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
